OPENAI_API_KEY = "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"
DISCOGS_TOKEN = "ARyyORRZGwCNDCULVgrdbkQjdHqRzfFTRjrWyRsO"

[gcp_service_account]
type = "service_account"
project_id = "abstract-flame-467623-r8"
private_key_id = "2c3ad0c2d3db7a7c6163d759f084c9e1605bea69"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCemv75653tMDbv
EPnjFRfBebEA4UtPWcDYRlz7JRqDZOX7IKFdUGO9RU1t2g2ZvMEY92msxBHr4kAT
H9RoAk8ooaQIrGY0VWi15vWC32dsc5z8xGVfIKY/yiCR+OaYWmnYl//HrdskCPBF
Hy+9g0+f5FRVtcCrMgUUNTnj7mw9eza7OcNetbyTex3l8dlGwepWWA+Q6aoA8eI9
ojnDhCtbjvb+WQdRyYtdSm5amDCUJz77d3eGNlRasvs03MZwVj2v7PyFr0gu8ZG2
G2r8o+M8uymWuFIWZDK1x2yg/aiWSTqntIis0kY+sOzrW4bkTB3WwIe/iygx2FkL
PXNybQt3AgMBAAECggEAPpH6HiFgS8bWHSku0/GpzgeSlzzKJ5NKe2gC3YdNNuHS
wugkELqapnwVKE26SNjIuu88Ts6JHWxEB+dqNeAXV3mxS0SsC2BYb06es5Mr64KO
v79BGK66N3cnsz6kxh0BHdQVMbK6PbSTCUnc3SBVBMigprGNwVv52feHj46rP/Nh
bkR/OOuDP3gf0133FBVz05ngdTU2SAJ4hg5CfwB9Ir8Meo59/CW1JNDrojlEoHe2
WC91fIg08qNjaS5fVLugW7Is6f88PAoGZ010UvqQVIkI6swbwzcF5UCoUjCcXGy8
NQiJ9Iqnlj9s/mRrx5PvlgUUOGE1mG7hj13ac1+goQKBgQDKYVB2uJgxJyzr6q9W
oDl+I1ugb1YgOKwzM5i5zgvnb2xs5RW5ikOKG8CWMb+wTQxXtlEvwMOdoOX1pwdz
IGlfj8UET0xuqjjIPBu+6/6kyfjrlug25RNr/V9CHIQfaNW/9mpmjwyJquodNY9g
c6jvxOpgLVryb8etKMybC/rJ1wKBgQDIoJv1WP1jO5iRY1ohjieqWw+GE8MPlbyw
uOLS5ZAlgyqmzB16vG6KTut24pmbmo6cKGmFKoBl3wM3qQPm+6xbq1eTQR92WLtH
H8l2+ntgh0p+PgYxY4TCJKFmvskmHK6M+mKspfZfMQ2M+vh7ktrngvXVDohp0vPV
S523T9XXYQKBgEUoCfH31HH/fBdGBBKq/9p9xKLHSPwLwbRhblAX+/NjHP79LXZQ
rBG2uBHbADEDszMJ5yZVTcNApzRRlncd3UQ9gcqeOnUaj/rEp4qPZF31cq02zTVt
BD0DwRh7XB7LmTdWwjc3rMYidIv0sID6JQGCHcEt3oU381jVt01IQ7PTAoGAe/hC
ZmiGqjq5G514pCNi/zEldoPflFHCNrEH96lCWOuj/01BKgYlh/EcLmn24N+wH24Z
Rd/tVwVmx434i1IYPsyxYJxtBIPvtRM/OfWtJwhyT2+kBACqmAxqb0KUqKgwc4yE
TIqAonF9HhA2WqVz/no9zVkdkcZ4RORkoFEEogECgYEAi4sxdDQ54ydiyyY7Lwv2
ghlWtftdFqlBUJr3txBksFPh4wMaVvoRdYn/wBugjUbjldFZ1SKWaLOq2phz6wck
qRcmBEe+0bwpXNbpY0GBJmxlArXhKLhG8V4pz1DgXz9/A1ghdiOzor2/Z0s5h1vJ
+IunVrzM7Zeg/74egevz2lc=
-----END PRIVATE KEY-----"""
client_email = "streamlit-tracker@abstract-flame-467623-r8.iam.gserviceaccount.com"
client_id = "102612677628176460209"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-tracker%40abstract-flame-467623-r8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
